### PR TITLE
Initial steps for a Python 3 port [incomplete]

### PR DESCRIPTION
**Pull request by raphaelm**
This is an initial try at a Python 3 port of xlutils. I don't know the codebase well enough to get it done completely and don't have the time to learn the missing parts, but this might already make it easier for you if you want to do a port (i'd love to see one).

Current teststatus is: FAILED (errors=2, failures=4)

A few remarks:

* I commented out the few usages of ``errorhandler``, as it doesn't seem that important to mee and would have to be ported first.
* The doctests don't seem to work due to changes in nose

### CODE REVIEW

**Comment by fbender** [comment]
@raphaelm are you still working on this?

**Comment by raphaelm** [comment]
No, I'm afraid I'm not. I couldn't resolve the failing tests in time and we went for another solution without this package in the project.

**Comment by cjw296** [comment]
Just a quick update: as of 2.0.0, xlutils is now Python 3 compatible.

**Comment by raphaelm** [comment]
Awesome!

**Pull request closed without merging**
